apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
spec:
  containers:
  - name: iperf3-server
    image: iperf3-server:0.1a
    ports:
    - containerPort: 5201
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-server-service
spec:
  type: NodePort
  selector:
    app: iperf3-server
  ports:
  - protocol: TCP
    port: 5201          # The port exposed within the cluster
    targetPort: 5201    # The port the Pod is listening on
    nodePort: 30001     # The NodePort to expose the service externally
