apiVersion: v1
kind: Pod
metadata:
  name: iperf3-client
spec:
  containers:
  - name: iperf3-client
    image: iperf3-client:0.1a
    env:
    - name: CUSTOMER_PORT
      value: 3001          
    args:
    - /bin/sh
    - -c
    - |
      while true; do
        iperf3 -c 172.254.102.101 -p $CUSTOMER_PORT
        sleep 10;
      done       
