# Pod definition for iperf3-server
apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
  labels:
    app: iperf3-server
spec:
  containers:
  - name: iperf3-server
    image: iperf3-server:0.1a
    ports:
    - containerPort: 5201

---

# Service definition for iperf3-server
apiVersion: v1
kind: Service
metadata:
  name: iperf3-server-service
spec:
  type: NodePort
  selector:
    app: iperf3-server
  ports:
  - protocol: TCP
    port: 5201
    targetPort: 5201
    nodePort: 30001
