apiVersion: topo.kubenet.dev/v1alpha1
kind: Topology
metadata:
  name: kubenet
  namespace: default
spec:
  defaults:
    platformType: ixrd3
    provider: srlinux.nokia.com
    region: region1
    site: us-east
    version: 24.7.2
  links:
  - endpoints:
    - adaptor: sfp
      endpoint: 1
      node: node2
      port: 2
    - adaptor: sfp
      endpoint: 1
      node: node3
      port: 2
  - endpoints:
    - adaptor: sfp
      endpoint: 1
      node: node3
      port: 1
    - adaptor: sfp
      endpoint: 1
      node: node4
      port: 1
  nodes:
  - name: node1
  - name: node2
