apiVersion: v1
kind: ServiceAccount
metadata:
  name: iperf-server-controller-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: iperf-server-role
rules:
  - apiGroups: ["example.com"]
    resources: ["iperfservers"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "update", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iperf-server-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: iperf-server-controller-sa
    namespace: default
roleRef:
  kind: Role
  name: iperf-server-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-server-controller
  namespace: default
spec:
  serviceAccountName: iperf-server-controller-sa
  initContainers:
    - name: install-kubernetes-client
      image: python:3.9
      command:
        - /bin/sh
        - -c
        - |
          pip install --target /app kubernetes
      volumeMounts:
        - name: app-volume
          mountPath: /app
  containers:
    - name: iperf-server-controller
      image: python:3.9
      command: ["python", "/app/controller.py"]
      volumeMounts:
        - name: app-volume
          mountPath: /app
        - name: config-volume
          mountPath: /app/controller.py
          subPath: controller.py
  volumes:
    - name: app-volume
      emptyDir: {}
    - name: config-volume
      configMap:
        name: iperf-server-controller
