apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iperfclients.example.com
spec:
  group: example.com
  names:
    kind: IperfClient
    listKind: IperfClientList
    plural: iperfclients
    singular: iperfclient
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetIP:
                  type: string
                initPort:
                  type: integer
                endPort:
                  type: integer
                image:
                  type: string

