# This is the DiscoveryRule
# It is used to find devices (in this case statically defiened addresses) and to tie the different profiles and credentials together.
# The DIscovery controller will create target resources for the discovered devices.
apiVersion: inv.sdcio.dev/v1alpha1
kind: DiscoveryRule
metadata:
  name: basic-usage
  namespace: default
spec:
  period: 1m
  addresses:
  - address: 172.21.0.200
    hostName: dev1
  - address: 172.21.0.201
    hostName: dev2
  discoveryProfile:
    credentials: srl.nokia.sdcio.dev 
    connectionProfiles:
    - gnmi-proto-conn
  targetConnectionProfiles:
  - credentials: srl.nokia.sdcio.dev 
    connectionProfile: gnmi-proto-conn
    syncProfile: gnmi-get-json-ietf-sync
  targetTemplate:
    labels:
      sdcio.dev/region: us-east