# SDC needs to access the devices. It therefore requires credentials to
# get access to the device. In this case it is username and password.
apiVersion: v1
kind: Secret
metadata:
  name: srl.nokia.sdcio.dev 
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: NokiaSrl1!