apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata:
  name: dev1-system0                          # The name of the config resource
  namespace: default
  labels:
    config.sdcio.dev/targetName: dev1         # The target name to apply this config to
    config.sdcio.dev/targetNamespace: default
spec:
  priority: 10                                # priority to use as a 
  config:
  - path: /                                   # path where config applies to, this case root level config
    value:                                    # the sub structure of value is the actual device config in yaml
      interface:
      - name: "system0"
        admin-state: "shutdown"
        description: "k8s-system0-dummy"