apiVersion: config.sdcio.dev/v1alpha1
kind: ConfigSet
metadata:
  name: vlan-configs
  namespace: default
spec:
  target:
    targetSelector:                   
      matchLabels:                          # match labels define labels of targets, for which this configset applies
        sdcio.dev/region: us-east           # this case for us-east reagion.
  priority: 10
  config:
  - path: /
    value:
      interface:
      - name: ethernet-1/1
        admin-state: "enable"
        description: "intent-vlan-configs"
        vlan-tagging: true
        subinterface:
        - index: 2
          type: bridged
          vlan:
            encap:
              single-tagged:
                vlan-id: 2
        - index: 3
          type: bridged
          vlan:
            encap:
              single-tagged:
                vlan-id: 3
        - index: 4
          type: bridged
          vlan:
            encap:
              single-tagged:
                vlan-id: 4